apiVersion: v1
kind: Service
metadata:
  name: api-cluster-ip
  labels:
    service: api-cluster-ip

spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  - name: grpc
    port: 4005
    targetPort: 4005
  selector:
    app: api