version: "3"

services:
    redis:
        container_name: redis
        image: redis:alpine

    db:
        container_name: db
        restart: unless-stopped
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: streamer
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: gotest
        ports:
            - 3306:3306
        expose:
            - 3306
        volumes:
            - storage:/var/lib/mysql

    rtmp:
        container_name: rtmp
        links:
            - web
        build:
            context: .
            dockerfile: ./scripts/rtmp/Dockerfile
        volumes:
            - public:/hls-preview/
        entrypoint: ./scripts/wait-for-it.sh web:80 -- air -c ./scripts/rtmp/.air.toml
        restart: unless-stopped
        ports:
            - "1935:1935"
        expose:
            - 1935
        environment:
            GRPC_HOST: web
            REDIS_HOST: redis

    web:
        container_name: web
        restart: always
        links:
            - db
            - redis
        build:
            context: .
            dockerfile: ./scripts/web/Dockerfile
        entrypoint: ./scripts/wait-for-it.sh db:3306 -- air -c ./scripts/web/.air.toml
        volumes:
            - ./:/go/src/github.com/praveen001/go-rtmp-web-server
        restart: unless-stopped
        expose:
            - 4005
            - 5000
        environment:
            MYSQL_HOST: db
            MYSQL_USER: streamer
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: gotest
            REDIS_HOST: redis
        env_file:
            - ./scripts/configs.env

    ui:
        container_name: ui
        build:
            context: .
            dockerfile: ./scripts/ui/Dockerfile
        entrypoint: yarn start
        volumes:
            - ./frontend/src/:/ui/src
        restart: unless-stopped
        expose:
            - 8080

    nginx:
        container_name: nginx
        links:
            - web
            - ui
        build:
            context: .
            dockerfile: ./scripts/nginx/Dockerfile
        volumes:
            - public:/usr/share/nginx/html/hls-preview/
        ports:
            - "80:80"
        expose:
            - 80

volumes:
    public:
    storage:
