version: "3"

services:
    redis:
        container_name: redis
        image: redis:alpine

    db:
        container_name: db
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: streamer
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: gotest

    rtmp:
        container_name: rtmp
        links:
            - web
        build:
            context: .
            dockerfile: ./scripts/rtmp/Dockerfile
        volumes:
            - public:/hls-preview/
        entrypoint: ./wait-for-it.sh web:80 -- ./rtmp/init.sh
        restart: unless-stopped
        ports:
            - "1935:1935"
        expose:
            - 1935
        environment:
            GRPC_HOST: web
            REDIS_HOST: redis

    web:
        container_name: web
        links:
            - db
            - redis
        build:
            context: .
            dockerfile: ./scripts/web/Dockerfile
        entrypoint: ./wait-for-it.sh db:3306 -- ./web/init.sh
        restart: unless-stopped
        expose:
            - 4005
            - 5000
        environment:
            MYSQL_HOST: db
            MYSQL_USER: streamer
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: gotest
            REDIS_HOST: redis
        env_file:
            - ./scripts/configs.env

    ui:
        container_name: ui
        build:
            context: .
            dockerfile: ./scripts/ui/Dockerfile
        volumes:
            - public:/usr/share/nginx/html/hls-preview/
        restart: unless-stopped
        ports:
            - "80:80"
        expose:
            - 80

volumes:
    public:
