apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-deployment
  labels:
    app: api

spec:
  selector:
    matchLabels:
      app: api

  template:
    metadata:
      labels:
        app: api

    spec:
      containers:
      - name: multi-streamer-api
        image: praveenraj9495/multi-streamer-api:v0.2.0
        env:
        - name: API_ENDPOINT
          value: http://localhost
        - name: UI_ENDPOINT
          value: http://localhost
        - name: MYSQL_USER
          value: multi-streamer
        - name: MYSQL_PASSWORD
          value: multi-streamer
        - name: MYSQL_HOST
          value: mysql-cluster-ip
        - name: MYSQL_DATABASE
          value: multi-streamer
        - name: REDIS_HOST
          value: redis-cluster-ip
        - name: YOUTUBE_CLIENT_ID
          value: 813004830141-3tamleghb88jb8c38pjdfbobp2mg7qt3.apps.googleusercontent.com
        - name: YOUTUBE_CLIENT_SECRET
          value: 
        - name: TWITCH_CLIENT_ID
          value: d72o1jp8j07z6z3km9zxaz266us9lx
        - name: TWITCH_CLIENT_SECRET
          value: mc6tzwdmpbapslalifmzycgpkn011w
        ports:
        - containerPort: 5000
        - containerPort: 4005